/**
 * Autogenerated by Thrift Compiler (0.10.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package xin.aitech.eckg.thrift.word2vector;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.lang.Exception;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-06-23")
public class similarWords implements org.apache.thrift.TBase<similarWords, similarWords._Fields>, java.io.Serializable, Cloneable, Comparable<similarWords> {

    private static final Logger _logger = LoggerFactory.getLogger(similarWords.class);

    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("similarWords");

    private static final org.apache.thrift.protocol.TField WORDS_FIELD_DESC = new org.apache.thrift.protocol.TField("words", org.apache.thrift.protocol.TType.LIST, (short) 1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new similarWordsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new similarWordsTupleSchemeFactory();

    public java.util.List<String> words; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        WORDS((short) 1, "words");

        private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // WORDS
                    return WORDS;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        public static _Fields findByName(String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final String _fieldName;

        _Fields(short thriftId, String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        public short getThriftFieldId() {
            return _thriftId;
        }

        public String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.WORDS, new org.apache.thrift.meta_data.FieldMetaData("words", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(similarWords.class, metaDataMap);
    }

    public similarWords() {
    }

    public similarWords(
            java.util.List<String> words) {
        this();
        this.words = words;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public similarWords(similarWords other) {
        if (other.isSetWords()) {
            java.util.List<String> __this__words = new java.util.ArrayList<String>(other.words);
            this.words = __this__words;
        }
    }

    public similarWords deepCopy() {
        return new similarWords(this);
    }

    @Override
    public void clear() {
        this.words = null;
    }

    public int getWordsSize() {
        return (this.words == null) ? 0 : this.words.size();
    }

    public java.util.Iterator<String> getWordsIterator() {
        return (this.words == null) ? null : this.words.iterator();
    }

    public void addToWords(String elem) {
        if (this.words == null) {
            this.words = new java.util.ArrayList<String>();
        }
        this.words.add(elem);
    }

    public java.util.List<String> getWords() {
        return this.words;
    }

    public similarWords setWords(java.util.List<String> words) {
        this.words = words;
        return this;
    }

    public void unsetWords() {
        this.words = null;
    }

    /** Returns true if field words is set (has been assigned a value) and false otherwise */
    public boolean isSetWords() {
        return this.words != null;
    }

    public void setWordsIsSet(boolean value) {
        if (!value) {
            this.words = null;
        }
    }

    public void setFieldValue(_Fields field, Object value) {
        switch (field) {
            case WORDS:
                if (value == null) {
                    unsetWords();
                } else {
                    setWords((java.util.List<String>) value);
                }
                break;

        }
    }

    public Object getFieldValue(_Fields field) {
        switch (field) {
            case WORDS:
                return getWords();

        }
        throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new IllegalArgumentException();
        }

        switch (field) {
            case WORDS:
                return isSetWords();
        }
        throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
        if (that == null)
            return false;
        if (that instanceof similarWords)
            return this.equals((similarWords) that);
        return false;
    }

    public boolean equals(similarWords that) {
        if (that == null)
            return false;
        if (this == that)
            return true;

        boolean this_present_words = true && this.isSetWords();
        boolean that_present_words = true && that.isSetWords();
        if (this_present_words || that_present_words) {
            if (!(this_present_words && that_present_words))
                return false;
            if (!this.words.equals(that.words))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetWords()) ? 131071 : 524287);
        if (isSetWords())
            hashCode = hashCode * 8191 + words.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(similarWords other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = Boolean.valueOf(isSetWords()).compareTo(other.isSetWords());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetWords()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.words, other.words);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("similarWords(");
        boolean first = true;

        sb.append("words:");
        if (this.words == null) {
            sb.append("null");
        } else {
            sb.append(this.words);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            _logger.error(te.getMessage(), te);
            throw new java.io.IOException(te);
        } catch (Exception e) {
            _logger.error(e.getMessage(), e);
        }
    }

    private static class similarWordsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public similarWordsStandardScheme getScheme() {
            return new similarWordsStandardScheme();
        }
    }

    private static class similarWordsStandardScheme extends org.apache.thrift.scheme.StandardScheme<similarWords> {

        public void read(org.apache.thrift.protocol.TProtocol iprot, similarWords struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // WORDS
                        if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                            {
                                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                                struct.words = new java.util.ArrayList<String>(_list8.size);
                                String _elem9;
                                for (int _i10 = 0; _i10 < _list8.size; ++_i10) {
                                    _elem9 = iprot.readString();
                                    struct.words.add(_elem9);
                                }
                                iprot.readListEnd();
                            }
                            struct.setWordsIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        public void write(org.apache.thrift.protocol.TProtocol oprot, similarWords struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.words != null) {
                oprot.writeFieldBegin(WORDS_FIELD_DESC);
                {
                    oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.words.size()));
                    for (String _iter11 : struct.words) {
                        oprot.writeString(_iter11);
                    }
                    oprot.writeListEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class similarWordsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        public similarWordsTupleScheme getScheme() {
            return new similarWordsTupleScheme();
        }
    }

    private static class similarWordsTupleScheme extends org.apache.thrift.scheme.TupleScheme<similarWords> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, similarWords struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetWords()) {
                optionals.set(0);
            }
            oprot.writeBitSet(optionals, 1);
            if (struct.isSetWords()) {
                {
                    oprot.writeI32(struct.words.size());
                    for (String _iter12 : struct.words) {
                        oprot.writeString(_iter12);
                    }
                }
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, similarWords struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(1);
            if (incoming.get(0)) {
                {
                    org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
                    struct.words = new java.util.ArrayList<String>(_list13.size);
                    String _elem14;
                    for (int _i15 = 0; _i15 < _list13.size; ++_i15) {
                        _elem14 = iprot.readString();
                        struct.words.add(_elem14);
                    }
                }
                struct.setWordsIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

